import Head from "next/head";
import React from "react";
import NavBar from "./_components/nav-bar";
import Carousel from "./_components/carousel";
import Cardpromo from "./_components/card-promo";
import Carddetails from "./_components/card-details";
import Benefits from "./_components/benefits";
import Newsletter from "./_components/newsletter";
import Highlights from "./_components/highlights";
import InstagramIcon from "@material-ui/icons/Instagram";
import TwitterIcon from "@material-ui/icons/Twitter";
import FacebookIcon from "@material-ui/icons/Facebook";
import { Button } from "@mui/material";
import Link from "next/link";

function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Casa da Joaninha</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <header>
            <nav>
              <NavBar></NavBar>
            </nav>
          </header>

          <div>   
            <Carousel></Carousel>

            <h2>DESTAQUES</h2>
            <Highlights></Highlights>

            <h2>NOSSOS BENEFÍCIOS</h2>
            <Benefits></Benefits>

            <Carddetails></Carddetails>

            <h2>PROMOÇÕES</h2>
            <Cardpromo></Cardpromo>
          </div>
        </div>
        <div>
          <h2>NEWSLETTER</h2>
          <Newsletter></Newsletter>
          <br></br>
          <Link href="/shopList">
              <Button variant="contained">PROXIMA PAGINA</Button>
            </Link>
        </div>
        <footer>
          <InstagramIcon></InstagramIcon>
          <TwitterIcon></TwitterIcon>
          <FacebookIcon></FacebookIcon>
          <br></br>© 2021 CASA DA JOANINHA
        </footer>
      </div>
    </>
  );
}

export default Home;
